version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/styles"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/packages/components"
    schedule:
      interval: "daily"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 1